### ISSUE TITLE
Fatal error: Fatal error: require(): Failed opening required '~/bulma-dash-docset-generator/vendor/autoload.php'

### ISSUE THREAD

**Issue by williamukoh** [lucacri/bulma-dash-docset-generator#1]
Followed your instruction as written. This error occurs. You might want to be more explicit with instructions on how to install and use

**Comment by lucacri** [comment]
Hello, it sounds like you didn't run `composer install`. Sorry I didn't specify it in the docs

**Comment by williamukoh** [comment]
I figured @lucacri. I just wanted to point that out to you. Great work
